"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Envelope(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class MetadataEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    TYPE_FIELD_NUMBER: _builtins.int
    ID_FIELD_NUMBER: _builtins.int
    PAYLOAD_FIELD_NUMBER: _builtins.int
    METADATA_FIELD_NUMBER: _builtins.int
    type: _builtins.str
    id: _builtins.str
    payload: _builtins.bytes
    @_builtins.property
    def metadata(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
    def __init__(
        self,
        *,
        type: _builtins.str = ...,
        id: _builtins.str = ...,
        payload: _builtins.bytes = ...,
        metadata: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "metadata", b"metadata", "payload", b"payload", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Envelope: _TypeAlias = Envelope  # noqa: Y015

@_typing.final
class Pit(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DELAY_FIELD_NUMBER: _builtins.int
    delay: _builtins.float
    def __init__(
        self,
        *,
        delay: _builtins.float = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["delay", b"delay"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Pit: _TypeAlias = Pit  # noqa: Y015

@_typing.final
class Pat(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    OK_FIELD_NUMBER: _builtins.int
    ok: _builtins.bool
    def __init__(
        self,
        *,
        ok: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ok", b"ok"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Pat: _TypeAlias = Pat  # noqa: Y015

@_typing.final
class Empty(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___Empty: _TypeAlias = Empty  # noqa: Y015
