# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from cvpa.protos import service_pb2 as cvpa_dot_protos_dot_service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cvpa/protos/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ManagedServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Channel = channel.stream_stream(
                '/cvpa.protos.ManagedService/Channel',
                request_serializer=cvpa_dot_protos_dot_service__pb2.Envelope.SerializeToString,
                response_deserializer=cvpa_dot_protos_dot_service__pb2.Envelope.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/cvpa.protos.ManagedService/Heartbeat',
                request_serializer=cvpa_dot_protos_dot_service__pb2.Pit.SerializeToString,
                response_deserializer=cvpa_dot_protos_dot_service__pb2.Pat.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/cvpa.protos.ManagedService/Shutdown',
                request_serializer=cvpa_dot_protos_dot_service__pb2.Empty.SerializeToString,
                response_deserializer=cvpa_dot_protos_dot_service__pb2.Empty.FromString,
                _registered_method=True)


class ManagedServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Channel(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ManagedServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Channel': grpc.stream_stream_rpc_method_handler(
                    servicer.Channel,
                    request_deserializer=cvpa_dot_protos_dot_service__pb2.Envelope.FromString,
                    response_serializer=cvpa_dot_protos_dot_service__pb2.Envelope.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=cvpa_dot_protos_dot_service__pb2.Pit.FromString,
                    response_serializer=cvpa_dot_protos_dot_service__pb2.Pat.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=cvpa_dot_protos_dot_service__pb2.Empty.FromString,
                    response_serializer=cvpa_dot_protos_dot_service__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cvpa.protos.ManagedService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cvpa.protos.ManagedService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ManagedService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Channel(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/cvpa.protos.ManagedService/Channel',
            cvpa_dot_protos_dot_service__pb2.Envelope.SerializeToString,
            cvpa_dot_protos_dot_service__pb2.Envelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cvpa.protos.ManagedService/Heartbeat',
            cvpa_dot_protos_dot_service__pb2.Pit.SerializeToString,
            cvpa_dot_protos_dot_service__pb2.Pat.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cvpa.protos.ManagedService/Shutdown',
            cvpa_dot_protos_dot_service__pb2.Empty.SerializeToString,
            cvpa_dot_protos_dot_service__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
