# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cvpa/protos/service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cvpa/protos/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x63vpa/protos/service.proto\x12\x0b\x63vpa.protos\"\x9d\x01\n\x08\x45nvelope\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\x12\x35\n\x08metadata\x18\x04 \x03(\x0b\x32#.cvpa.protos.Envelope.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x14\n\x03Pit\x12\r\n\x05\x64\x65lay\x18\x01 \x01(\x02\"\x11\n\x03Pat\x12\n\n\x02ok\x18\x01 \x01(\x08\"\x07\n\x05\x45mpty2\xb2\x01\n\x0eManagedService\x12;\n\x07\x43hannel\x12\x15.cvpa.protos.Envelope\x1a\x15.cvpa.protos.Envelope(\x01\x30\x01\x12/\n\tHeartbeat\x12\x10.cvpa.protos.Pit\x1a\x10.cvpa.protos.Pat\x12\x32\n\x08Shutdown\x12\x12.cvpa.protos.Empty\x1a\x12.cvpa.protos.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cvpa.protos.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENVELOPE_METADATAENTRY']._loaded_options = None
  _globals['_ENVELOPE_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_ENVELOPE']._serialized_start=43
  _globals['_ENVELOPE']._serialized_end=200
  _globals['_ENVELOPE_METADATAENTRY']._serialized_start=153
  _globals['_ENVELOPE_METADATAENTRY']._serialized_end=200
  _globals['_PIT']._serialized_start=202
  _globals['_PIT']._serialized_end=222
  _globals['_PAT']._serialized_start=224
  _globals['_PAT']._serialized_end=241
  _globals['_EMPTY']._serialized_start=243
  _globals['_EMPTY']._serialized_end=250
  _globals['_MANAGEDSERVICE']._serialized_start=253
  _globals['_MANAGEDSERVICE']._serialized_end=431
# @@protoc_insertion_point(module_scope)
