# -*- coding: utf-8 -*-

from typing import Final

CVPA_NO_DOTENV: Final[str] = "CVPA_NO_DOTENV"
CVPA_DOTENV_PATH: Final[str] = "CVPA_NO_DOTENV"

CVPA_COLORED_LOGGING: Final[str] = "CVPA_COLORED_LOGGING"
CVPA_SIMPLE_LOGGING: Final[str] = "CVPA_SIMPLE_LOGGING"

CVPA_LOGGING_STEP: Final[str] = "CVPA_LOGGING_STEP"
CVPA_LOGGING_SEVERITY: Final[str] = "CVPA_LOGGING_SEVERITY"

CVPA_HOME: Final[str] = "CVPA_HOME"

CVPA_USE_UVLOOP: Final[str] = "CVPA_USE_UVLOOP"
CVPA_DEBUG: Final[str] = "CVPA_DEBUG"
CVPA_VERBOSE: Final[str] = "CVPA_VERBOSE"

CVPA_AGENT_SLUG: Final[str] = "CVPA_AGENT_SLUG"
CVPA_AGENT_TOKEN: Final[str] = "CVPA_AGENT_TOKEN"
CVPA_AGENT_URL: Final[str] = "CVPA_AGENT_URL"

CVPA_SLOW_CALLBACK_DURATION: Final[str] = "CVPA_SLOW_CALLBACK_DURATION"
